ktor:
  application:
    modules:
      - com.osucad.server.messageOrderer.ApplicationKt.module
  deployment:
    port: 8080

osucad:
  redis:
    hostname: $REDIS_HOSTNAME
    port: "$REDIS_PORT:6379"